name: 02_workflows_events\
on: 
    # NOTE: by doing this, we are using the object syntax so we can customize each part differently, maybe the pull requests on different branches, maybe the push on another branches, etc
    push:
    pull_request:
    # schedule:
    #     - cron: '*/1 * * * *' # Every minute
    workflow_dispatch:
jobs:
    print-workflow-event:
        runs-on: ubuntu-latest
        steps:
            - name: Print workflow event
              run: | 
                echo "Workflow event: ${{ github.event_name }}"