name: 03_workflow_actions
on: 
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: listing codebase folder structure and files
              run: ls  -la 
        
            - name: setup go 
              uses: actions/setup-go@v4
              with:
                go-version: '1.24.2'
            
            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                path: |
                  ~/.cache/go-build
                  ~/go/pkg/mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                  ${{ runner.os }}-go-

            - name: instal dependencies
              run: go mod tidy
              working-directory: ./04_workflow_actions

            - name: run unit tests
              run: go test ./... -v
              working-directory: ./04_workflow_actions


            - name: Run tests with coverage
              run: go test ./... -coverprofile=coverage.out