name: 03_workflow_actions
on: 
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: listing codebase folder structure and files
              run: |
                  ls  
        